name: Build and Deploy

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'help-docs/**'
      - 'docusaurus.config.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build site
        run: yarn build
        env:
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
      
      - name: Build completed
        run: echo "Site built successfully. Algolia will be updated on next deployment." 